version: '3'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    restart: always
    privileged: true
    ports:
      - 8123:8123
    volumes:
      - $HASS_HOME/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    